/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { RigidBody } from "@react-three/rapier"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF("./chest.gltf")
  return (
    <RigidBody
      type="fixed"
      position={[0, -0.15, 0]}
      rotation={[Math.PI / 2, Math.PI * 2, 0]}
      restitution={0.2}
      friction={0}
    >
      <group scale={0.4}>
        <mesh
          geometry={nodes.Cube051.geometry}
          material={materials["Metal.085"]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube051_1.geometry}
          material={materials["BrownDark.053"]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube051_2.geometry}
          material={materials["Gold.006"]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube051_3.geometry}
          material={materials["Red.039"]}
          castShadow
          receiveShadow
        />
      </group>
    </RigidBody>
  )
}

useGLTF.preload("./chest.gltf")
