/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Denys Almaral (https://sketchfab.com/denysalmaral)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/african-pop-dance-free-animation-36155b1100184d37bff6c8490670c77c
Title: African Pop Dance Free Animation
*/

import React, { useEffect, useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import useGame from "../stores/useGame"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/lady.glb")

  const { actions } = useAnimations(animations, group)
  const phase = useGame((state) => state.phase)

  useEffect(() => {
    const action = actions["Take 001"]
    if (phase === "ended") {
      action.reset().fadeIn(0.5).play()
    } else if (phase === "ready") {
      action.stop()
    }
  }, [phase])

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.8}
      position={[1, 0.1, 0]}
      rotation-y={-Math.PI / 6}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="086ad4923a5442f790bc17eea9006b04fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="lpFemale_casual_G"
                  position={[0, 5, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <group name="rig_CharRoot" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.peopleColors}
                      skeleton={nodes.Object_9.skeleton}
                      castShadow
                      receiveShadow
                    />
                    <group
                      name="Object_8"
                      position={[0, 5, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/lady.glb")
