/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Denys Almaral (https://sketchfab.com/denysalmaral)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hype-dance-free-animation-1e1fe9a41b6c41e68fdba824cc348d03
Title: Hype Dance Free Animation
*/

import React, { useEffect, useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import useGame from "../stores/useGame"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/man.glb")
  const { actions } = useAnimations(animations, group)

  const phase = useGame((state) => state.phase)

  useEffect(() => {
    const action = actions["Take 001"]
    if (phase === "ended") {
      action.reset().fadeIn(0.5).play()
    } else if (phase === "ready") {
      action.stop()
    }
  }, [phase])

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={0.7}
      position={[-1, 0.07, 0]}
      rotation-y={Math.PI / 6}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="dance_hype_100ffbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="lpMaleG" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="rig_CharRoot" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.peopleColors}
                      skeleton={nodes.Object_9.skeleton}
                      castShadow
                      receiveShadow
                    />
                    <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/man.glb")
